### ISSUE TITLE
add description of target platform and layout to wiki pages

### ISSUE THREAD

**Issue by ghost** [OSU-CS361-W17/group10_project2#1]
add description of target platform and layout to wiki pages

**Comment by cascadeth** [comment]
May want to split these up into two different wiki pages.  Just a thought.  One page for the Target Platform / Users, and one for the actual layout

**Comment by cascadeth** [comment]
First draft looks good.  Page might need an update again once we all see what the final product looks like.

**Comment by cascadeth** [comment]
Left @beaversoft16  as assignee, but also made some tweaks to the wording that captured more of what our design was following.  Overall, looks like this issue can be closed.
