### ISSUE TITLE
Update Prototypes page to show final design decision

### ISSUE THREAD

**Issue by cascadeth** [OSU-CS361-W17/group10_project2#2]
We never indicated what the final design was going to be.  According to the job description, we need a clear indication of what it should be.

**Comment by ghost** [comment]
division of labor can be:
max: update wiki page containing final paper prototype
brandon, liv, nathan: each do one of: regular state, blank state, error state

after more code is written.

**Comment by cascadeth** [comment]
After @vorhut 's first pushes to make the design look more like our 3 best, I snagged a screen shot of the results and pasted them as our final design/prototype.  Clearly there is much to be built upon in this image, but this would be the core layout we should have started the project with.  

* Disregard close-reopen-close below; still open

**Comment by cascadeth** [comment]
Realized we can't do that, because it's not paper. Derp... Updating to paper, and adding 3 versions.

**Comment by cascadeth** [comment]
Finished earlier, forgot to post closure.
