### ISSUE TITLE
Pull everything up and right, to the horizontal

### ISSUE THREAD

**Issue by cascadeth** [OSU-CS361-W17/group10_project2#3]
The original design or "view" was very column biased.  For our 16:9 environment, a more horizontal approach would eliminate the need for scrolling, and consolidate everything to a nice widescreen layout.  

Ideally we would have the boards on one side of the screen, taking up most of the view, and the controls taking up the remaining space.  If there is any room left over, we might be able to squeeze in extra styling or graphics.

**Comment by TheNulls** [comment]
Updated files but board is no longer square. Needs additional work.

**Comment by cascadeth** [comment]
Looks like @vorhut got this pretty much squared away.  @LivVitale probably has some improvements up her sleeve too.

**Comment by LivVitale** [comment]
Further layout improvements implemented. Everything should be sitting where expected now. Closing issue.
