### ISSUE TITLE
Implement User Friendly / Intuitive Notifications

### ISSUE THREAD

**Issue by cascadeth** [OSU-CS361-W17/group10_project2#6]
Was talking with @LivVitale and @beaversoft16 over Slack and we thought it might be a good idea to design some way to show users a simple notification of their actions on the screen.  Obviously these messages can't come from the server, so @LivVitale mentioned [**_toastr_** ](https://github.com/CodeSeven/toastr)for simple, easy to develop client side notifications. 

@beaversoft16 mentioned he could get this up.

**Comment by ghost** [comment]
While not able to implement more intuitive notifications, added reminder to place ships first so user plays the game correctly.
